# Generated by Django 6.0.2 on 2026-02-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='exhibits/'),
        ),
    ]
