# Generated by Django 6.0.2 on 2026-02-17 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_alter_exhibit_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='exhibit',
            name='data_issues',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='deployment_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='design_choices',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='how_detected',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='inputs_assumptions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='intended_use',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='org_governance_issues',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='outputs_to_users',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='system_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='warnings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='what_went_wrong',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='who_affected',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.category'),
        ),
    ]
