# Generated by Django 6.0.2 on 2026-02-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_category_exhibit_data_issues_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibit',
            old_name='Category',
            new_name='category',
        ),
    ]
