# Generated by Django 6.0.2 on 2026-02-17 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_rename_category_exhibit_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='domain',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='failure_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='exhibit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='museum.exhibit'),
        ),
    ]
