# Generated by Django 5.2.11 on 2026-02-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_remove_exhibit_domain_exhibit_failure_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
