# Generated by Django 6.0.2 on 2026-03-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0006_answeroption_is_correct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhibit",
            name="file",
        ),
        migrations.AddField(
            model_name="exhibit",
            name="artefact1",
            field=models.FileField(
                blank=True, null=True, upload_to="exhibits/artefacts/"
            ),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="artefact2",
            field=models.FileField(
                blank=True, null=True, upload_to="exhibits/artefacts/"
            ),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="artefact3",
            field=models.FileField(
                blank=True, null=True, upload_to="exhibits/artefacts/"
            ),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="artefact4",
            field=models.FileField(
                blank=True, null=True, upload_to="exhibits/artefacts/"
            ),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="artefact5",
            field=models.FileField(
                blank=True, null=True, upload_to="exhibits/artefacts/"
            ),
        ),
    ]
