# Generated by Django 6.0.2 on 2026-03-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_answeroption_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
