# Generated by Django 6.0.2 on 2026-03-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0007_exhibit_view_count"),
        ("museum", "0007_remove_exhibit_file_exhibit_ai_system_artefact_and_more"),
    ]

    operations = []
