# Generated by Django 6.0.2 on 2026-03-13 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0008_merge_20260306_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibits', to='museum.category'),
        ),
    ]
