# Generated by Django 5.2.12 on 2026-03-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0009_category_display_image_category_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='static_image',
            field=models.CharField(blank=True, help_text='Path relative to static/, e.g. images/categories/my-image.png', max_length=200),
        ),
    ]
