# Generated by Django 6.0.2 on 2026-03-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0010_timelineevent"),
        ("museum", "0013_usersubmission"),
    ]

    operations = []
